# This is a basic workflow to help you get started with Actions

name: Setup

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      # Downloads all dependencies if they don't exist
      # Runs commands to install xschem, then the PDK files, then open xschem
      
      - name: Install Xschem and Dependencies 
        run: |
              sudo apt update
              sudo apt install -y tk8.6-dev libxpm-dev tcl8.6-dev libx11-dev flex
              git submodule add https://github.com/efabless/caravel_mpw-one.git
              export CARAVEL_ROOT=$GITHUB_WORKSPACE/caravel_mpw-one
              git submodule add https://github.com/google/skywater-pdk.git
              cd skywater-pdk
              sudo ./configure --with-sky130-source=~$GITHUB_WORKSPACE/skywater-pdk/libraries --with-sky130-local-path=~/cad/pdks
              
