# This is a basic workflow to help you get started with Actions

name: Setup

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      # Downloads all dependencies if they don't exist
      # Runs commands to install xschem, then the PDK files, then open xschem
      
      - name: Install Xschem and Dependencies 
        run: |
              sudo rm -rf /usr/share/dotnet
              sudo rm -rf "$AGENT_TOOLSDIRECTORY"
              sudo apt update
              sudo apt install -y tk8.6-dev libxpm-dev tcl8.6-dev libx11-dev flex libtool-bin libxaw7-dev libreadline6-dev libcairo2-dev
              git submodule add https://github.com/RTimothyEdwards/magic
              git submodule add git://opencircuitdesign.com/open_pdks
              cd open_pdks
              ./configure --enable-sky130-pdk --enable-sram-sky130
              

              
              
              
