# This is a basic workflow to help you get started with Actions

name: Setup

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      # Downloads all dependencies if they don't exist
      # Runs commands to install xschem, then the PDK files, then open xschem
      
      - name: Install Xschem and Dependencies 
        run: |
              sudo rm -rf /usr/share/dotnet
              sudo rm -rf "$AGENT_TOOLSDIRECTORY"
              sudo apt update
              sudo apt install -y tk8.6-dev libxpm-dev tcl8.6-dev libx11-dev flex libtool-bin libxaw7-dev libreadline6-dev libcairo2-dev
              git submodule add https://github.com/google/skywater-pdk.git
              cd skywater-pdk
              SUBMODULE_VERSION=latest make submodules -j3 || make submodules -j1
              make timing
              git submodule add https://github.com/RTimothyEdwards/magic
              sudo apt-get install magic
              git submodule add https://git.code.sf.net/p/ngspice/ngspice ngspice_git
              cd ngspice_git
              mkdir release
              ./autogen.sh
              cd release
              ../configure --with-x --enable-xspice --disable-debug --enable-cider --with-readline=yes --enable-openmp --enable-osdi
              make
              sudo make install
              cd ..
              cd ..
              git submodule add git://opencircuitdesign.com/open_pdks
              cd open_pdks
              ./configure --enable-sky130-pdk --enable-sram-sky130
              

              
              
              
