# This is a basic workflow to help you get started with Actions

name: Setup

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Downloads all dependencies if they don't exist
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: tk8.6-dev libxpm-dev tcl8.6-dev libtk-dev libx11-dev flex
          version: 1.0

      # Runs commands to install xschem, then the PDK files, then open xschem
        
      - name: Create 
        run: |
              git submodule add https://github.com/google/skywater-pdk.git
              cd ~/work/sky130_schematics/sky130_schematics/skywater-pdk
              sudo ./configure --with-sky130-source=~/work/sky130_schematics/sky130_schematics/skywater-pdk/libraries --with-sky130-local-path=~/cad/pdks
