# This is a basic workflow to help you get started with Actions

name: Setup

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "open_pdks_testing" ]
  # pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      # Downloads all dependencies if they don't exist
      # Runs commands to install xschem, then the PDK files, then open xschem
      
      - name: Install Dependencies 
        run: |
              sudo rm -rf /usr/share/dotnet
              sudo rm -rf "$AGENT_TOOLSDIRECTORY"
              sudo apt-get update
              sudo apt-get install -y tk8.6-dev libxpm-dev tcl8.6-dev libx11-dev flex libtool-bin libxaw7-dev libreadline6-dev libcairo2-dev
      - name: Install magic
        run: | 
              git clone --depth 1 https://github.com/RTimothyEdwards/magic
              cd magic
              ./configure
              make database/database.h
              make -j$(nproc)
      - name: Install skywater-pdk Libraries     
        run: |
              cd $GITHUB_WORKSPACE
              git clone --depth 1 https://github.com/google/skywater-pdk.git
              cd skywater-pdk
              SUBMODULE_VERSION=latest make submodules -j3 || make submodules -j1
              make timing
      - name: Install ngspice
        run: |
              cd $GITHUB_WORKSPACE
              git submodule add git://git.code.sf.net/p/ngspice/ngspice
              cd ngspice
              mkdir release
              ./autogen.sh
              cd release
              ../configure --with-x --enable-xspice --disable-debug --enable-cider --with-readline=yes --enable-openmp --enable-osdi
              make
      - name: Generate PDK files
        run: |
              cd $GITHUB_WORKSPACE
              git submodule add git://opencircuitdesign.com/open_pdks
              cd open_pdks
              ./configure --enable-sky130-pdk --enable-sram-sky130
              

              
              
              
