# This is a basic workflow to help you get started with Actions

name: Setup

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    # Temporarily restricted to testing branch, as otherwise concurrent runs happen every push
    branches: [ "open_pdks_testing" ]
  # pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Note: Generate PDK files sent inside repo, this is done just for testing and should be removed before going global
    steps:
      - uses: actions/checkout@v4 
      - name: Free Memory
        run: |
              sudo rm -rf /usr/share/dotnet
              sudo rm -rf "$AGENT_TOOLSDIRECTORY"        
      
      - name: Install Dependencies 
        run: |
              sudo apt-get update
              sudo apt-get install -y tk8.6-dev libxpm-dev tcl8.6-dev libx11-dev flex libtool-bin libxaw7-dev libreadline6-dev libcairo2-dev

      # Run fails; magic not found; only sudo apt-get install magic solved it; both necessary?
      - name: Install magic
        run: | 
              git clone --depth 1 https://github.com/RTimothyEdwards/magic
              cd magic
              ./configure
              make database/database.h
              make -j$(nproc)
              sudo apt-get install magic
      
      - name: Install ngspice
        run: |
              git clone --depth 1 git://git.code.sf.net/p/ngspice/ngspice
              cd ngspice
              mkdir release
              ./autogen.sh
              cd release
              ../configure --with-x --enable-xspice --disable-debug --enable-cider --with-readline=yes --enable-openmp --enable-osdi
              make
      
      # Removed make timing
        # Unclear is necessary, could be either, requires testing
      - name: Install skywater-pdk Libraries     
        run: |
              git clone https://github.com/google/skywater-pdk.git
              cd skywater-pdk
              SUBMODULE_VERSION=latest make submodules -j3 || make submodules -j1

      # Unclear if PDK files generated
      - name: Generate PDK files
        run: |
              git clone --depth 1 git://opencircuitdesign.com/open_pdks
              cd open_pdks
              ./configure --prefix=${{ github.workspace }}/open_pdks
              make
              sudo make install
              make veryclean

      - name: Verify Installation
        run: |
              git clone --depth 1 https://github.com/d-m-bailey/sky130_fd_io.git
              xschem --log test.log <<EOF
              xschem load f sky130_fd_io/top_gpiov2.sch 
              xschem exit closewindow force
              EOF
              grep -q "Symbol not found" test.log && exit 1
